#!/bin/bash

# WavesOS Installation Script - Packages Library
# Contains all package installation functions consolidated from system.sh and desktop.sh

install_base_system() {
    section_header "System • Base Packages"
    log "Installing base system packages..."
    
    local base_packages=(
        base
base-devel
linux
linux-headers
linux-firmware
linux-firmware-whence
linux-firmware-marvell
linux-api-headers
glibc
gcc
gcc-libs
binutils
gawk
make
autoconf
autoconf-archive
automake
bison
flex
m4
patch
pkgconf
filesystem
coreutils
util-linux
util-linux-libs
procps-ng
psmisc
sed
grep
findutils
which
tar
gzip
bzip2
xz
lz4
lzo
lzop
zlib
zlib-ng
zstd
bash
shadow
sudo
systemd
systemd-libs
systemd-sysvcompat
systemd-resolvconf
pam
pambase
dbus
dbus-broker
dbus-broker-units
dbus-glib
dbus-units
intel-ucode
amd-ucode
alsa-lib
alsa-card-profiles
alsa-topology-conf
alsa-ucm-conf
alsa-utils
mesa
vulkan-icd-loader
xf86-input-libinput
xorg-server
xorg-server-common
xorg-setxkbmap
xorg-xauth
xorg-xinit
xorg-xkbcomp
xorg-xmodmap
xorg-xprop
xorg-xrandr
xorg-xrdb
xorg-xset
xorg-xwayland
xorgproto
xkeyboard-config
xorg-fonts-encodings
hwdata
pciutils
usbutils
lsscsi
smartmontools
hdparm
dmidecode
lm_sensors
lsof
strace
perf
networkmanager
nm-connection-editor
network-manager-applet
dhcpcd
iproute2
iptables
nftables
iputils
wireless-regdb
wireless_tools
wpa_supplicant
iw
iwd
openssh
curl
wget
rsync
pipewire
pipewire-alsa
pipewire-audio
pipewire-jack
pipewire-pulse
wireplumber
pavucontrol
pamixer
playerctl
bluez-libs
usbredir
upower
udisks2
efibootmgr
efivar
grub
syslinux
arch-install-scripts
pacman
pacman-contrib
pacman-mirrorlist
    )
    
    show_progress 1 3 "Installing base system..."
    if ! pacstrap /mnt "${base_packages[@]}"; then
        error "Failed to install base system packages"
    fi
    
    success "Base system installed successfully"
}

install_bootloader_packages() {
    section_header "System • Bootloader"
    log "Installing bootloader packages..."
    
    if [ "$BOOT_MODE" = "uefi" ]; then
        show_progress 2 3 "Installing UEFI bootloader..."
        if ! pacstrap /mnt grub efibootmgr dosfstools; then
            error "Failed to install UEFI bootloader packages"
        fi
    else
        show_progress 2 3 "Installing BIOS bootloader..."
        if ! pacstrap /mnt grub; then
            error "Failed to install BIOS bootloader packages"
        fi
    fi
    
    success "Bootloader packages installed"
}

install_graphics_drivers() {
    section_header "System • Graphics"
    log "Graphics driver selection:"
    echo "1) Intel (open-source)"
    echo "2) AMD (open-source)"
    echo "3) NVIDIA (proprietary)"
    echo "4) NVIDIA (open-source nouveau)"
    echo "5) Generic/VM (VESA)"
    
    read -p "Select graphics driver (1-5): " GPU_CHOICE
    
    case $GPU_CHOICE in
        1) gpu_packages=(xf86-video-intel intel-media-driver vulkan-intel) ;;
        2) gpu_packages=(xf86-video-amdgpu mesa vulkan-radeon libva-mesa-driver) ;;
        3) gpu_packages=(nvidia nvidia-utils nvidia-settings) ;;
        4) gpu_packages=(xf86-video-nouveau mesa) ;;
        5) gpu_packages=(xf86-video-vesa mesa) ;;
        *) gpu_packages=(xf86-video-vesa mesa) ;;
    esac
    
    show_progress 3 3 "Installing graphics drivers..."
    if ! pacstrap /mnt "${gpu_packages[@]}"; then
        warning "Some graphics packages failed to install"
    fi
    
    success "Graphics drivers installed"
}

# Merged comprehensive packages function (replaces both common_desktop and custom packages)
install_comprehensive_packages() {
    section_header "System • Comprehensive Package Installation"
    log "Installing WavesOS comprehensive package set..."
    
    local wavesos_packages=(
        # Complete package set from packages.x86_64 (excluding base system packages)
        aalib
        abseil-cpp
        acl
        aom
        appstream
        aquamarine
        archinstall
        archiso
        archlinux-keyring
        atkmm
        attica
        attr
        audit
        augeas
        autoconf
        autoconf-archive
        automake
        avahi
        b43-fwcutter
        babl
        baloo
        baloo-widgets
        bat
        bcachefs-tools
        bind
        binutils
        bison
        blas
        bolt
        breeze-icons
        brltty
        broadcom-wl
        brotli
        btop
        btrfs-progs
        bubblewrap
        bzip2
        c-ares
        ca-certificates
        ca-certificates-mozilla
        ca-certificates-utils
        cairo
        cairomm
        cairomm-1.16
        capstone
        cava
        cdparanoia
        cdrtools
        chromaprint
        chromium
        cifs-utils
        clang
        cliphist
        clonezilla
        clutter
        clutter-gst
        clutter-gtk
        cmark
        cloud-init
        cogl
        compiler-rt
        composefs
        convertlit
        coreutils
        cpio
        cracklib
        cryptsetup
        ctags
        curl
        darkhttpd
        dav1d
        db5.3
        dbus
        dbus-broker
        dbus-broker-units
        dbus-glib
        dbus-units
        dconf
        ddrescue
        debootstrap
        debugedit
        default-cursors
        desktop-file-utils
        device-mapper
        dhcpcd
        dialog
        diffutils
        distro-info
        distro-info-data
        dkms
        dleyna
        dmraid
        dnsmasq
        docbook-xml
        docbook-xsl
        dosfstools
        double-conversion
        dtc
        duktape
        e2fsprogs
        ebook-tools
        editorconfig-core-c
        edk2-aarch64
        edk2-arm
        edk2-ovmf
        edk2-shell
        efibootmgr
        efivar
        egl-gbm
        egl-wayland
        egl-x11
        eglexternalplatform
        elfutils
        ell
        enchant
        erofs-utils
        espeakup
        ethtool
        evolution-data-server
        exempi
        exfatprogs
        exiv2
        exo
        expat
        eza
        f2fs-tools
        faac
        faad2
        fakeroot
        fastfetch
        fatresize
        ffmpeg
        ffmpegthumbnailer
        ffnvcodec-headers
        fftw
        figlet
        file
        filesystem
        findutils
        flac
        flatpak
        flex
        fluidsynth
        fmt
        folks
        fontconfig
        foot-terminfo
        freeglut
        freetype2
        frei0r-plugins
        fribidi
        fsarchiver
        fuse-common
        fuse2
        fuse3
        fzf
        gawk
        gc
        gcc
        gcc-libs
        gcr
        gcr-4
        gd
        gdbm
        gdk-pixbuf2
        gegl
        geocode-glib-2
        geocode-glib-common
        gettext
        gfxstream
        ghostscript
        giflib
        git
        gjs
        glib-networking
        glib2
        glib2-docs
        glibc
        glibmm
        glibmm-2.68
        glm
        glslang
        glu
        glusterfs
        gmime3
        gmp
        gnu-free-fonts
        gnulib-l10n
        gnupg
        gnutls
        go
        gobject-introspection-runtime
        gom
        gpart
        gperftools
        gpm
        gpgme
        gpgmepp
        gptfdisk
        granite
        graphene
        graphite
        graphviz
        grep
        grilo
        groff
        grub
        gsettings-desktop-schemas
        gsettings-system-schemas
        gsfonts
        gsm
        gsound
        gspell
        gssdp
        gst-plugin-pipewire
        gst-plugins-bad
        gst-plugins-bad-libs
        gst-plugins-base
        gst-plugins-base-libs
        gst-plugins-good
        gstreamer
        gtest
        gtk-doc
        gtk-layer-shell
        gtk-update-icon-cache
        gtk-vnc
        gtk2
        gtk3
        gtk4
        gtkmm-4.0
        gtkmm3
        gtksourceview4
        gtksourceview5
        gts
        guestfs-tools
        guile
        gum
        gupnp
        gupnp-av
        gupnp-dlna
        gupnp-igd
        gvfs
        gvfs-mtp
        gzip
        harfbuzz
        harfbuzz-icu
        hdparm
        hicolor-icon-theme
        hidapi
        highway
        hivex
        htop
        hwdata
        hyphen
        hyperv
        iana-etc
        icu
        ijs
        imagemagick
        imath
        imlib2
        iniparser
        iproute2
        iptables
        iputils
        ipython
        irssi
        iso-codes
        iwd
        jansson
        jasper
        jbig2dec
        jbigkit
        jfsutils
        jq
        js128
        json-c
        json-glib
        jsoncpp
        jsonrpc-glib
        karchive
        kauth
        kbd
        kbookmarks
        kcmutils
        kcodecs
        kcolorscheme
        kcompletion
        kconfig
        kconfigwidgets
        kcoreaddons
        kcrash
        kdbusaddons
        kdnssd
        kdsoap-qt6
        kdsoap-ws-discovery-client
        keyutils
        kfilemetadata
        kglobalaccel
        kguiaddons
        ki18n
        kiconthemes
        kidletime
        kio
        kio-extras
        kirigami
        kitemviews
        kitty
        kitty-shell-integration
        kitty-terminfo
        kjobwidgets
        kmod
        knewstuff
        knotifications
        kpackage
        kparts
        krb5
        kservice
        ktextwidgets
        kuserfeedback
        kvantum
        kvantum-qt5
        kwallet
        kwidgetsaddons
        kwindowsystem
        kxmlgui
        l-smash
        lame
        lapack
        lcms2
        ldb
        ldns
        leancrypto
        lensfun
        less
        lftp
        libfido2
        libusb-compat
        licenses
        lilv
        linux-atm
        livecd-sounds
        llhttp
        llvm-libs
        lm_sensors
        lmdb
        localsearch
        lrzip
        lsof
        lsscsi
        lua
        lua51-lpeg
        luajit
        lv2
        lvm2
        lxappearance
        lynx
        lz4
        lzo
        lzop
        m4
        make
        man-db
        man-pages
        mc
        md4c
        mdadm
        media-player-info
        memtest86+
        memtest86+-efi
        mesa
        meson
        minizip
        mjpegtools
        mkinitcpio
        mkinitcpio-archiso
        mkinitcpio-busybox
        mkinitcpio-nfs-utils
        mobile-broadband-provider-info
        modemmanager
        mpdecimal
        mpfr
        mpg123
        mpv
        mpv-mpris
        msgpack-c
        mtdev
        mtools
        mujs
        multipath-tools
        nano
        nbd
        ncurses
        ndctl
        ndisc6
        neon
        neovim
        netpbm
        nettle
        network-manager-applet
        networkmanager
        nfs-utils
        nftables
        nilfs-utils
        ninja
        nm-connection-editor
        nmap
        node-gyp
        nodejs
        nodejs-nopt
        noto-fonts
        noto-fonts-emoji
        npm
        npth
        nspr
        nss
        ntfs-3g
        numactl
        nvme-cli
        nwg-look
        ocl-icd
        oniguruma
        openal
        opencore-amr
        openconnect
        openexr
        openh264
        openjpeg2
        openpgp-card-tools
        openssh
        openssl
        openvpn
        opus
        orc
        os-prober
        osinfo-db
        ostree
        p11-kit
        pacman
        pacman-contrib
        pacman-mirrorlist
        pahole
        pam
        pambase
        pamixer
        pango
        pangomm
        pangomm-2.48
        parallel
        partclone
        parted
        partimage
        patch
        pavucontrol
        pciutils
        pcre
        pcre2
        pcsclite
        perf
        perl
        perl-error
        perl-libintl-perl
        perl-mailtools
        perl-timedate
        phodav
        phonon-qt6
        pinentry
        pipewire
        pipewire-alsa
        pipewire-audio
        pipewire-jack
        pipewire-pulse
        pixman
        pkgconf
        plasma-activities
        playerctl
        polkit
        polkit-gnome
        polkit-kde-agent
        polkit-qt6
        poppler
        poppler-data
        poppler-glib
        poppler-qt6
        popt
        portaudio
        power-profiles-daemon
        ppp
        pptpclient
        procps-ng
        protobuf
        psmisc
        pugixml
        pv
        python
        python-aiofiles
        python-argcomplete
        python-asttokens
        python-atspi
        python-attrs
        python-autocommand
        python-babel
        python-build
        python-cachecontrol
        python-cachy
        python-cairo
        python-cffi
        python-charset-normalizer
        python-cleo
        python-colorama
        python-configobj
        python-crashtest
        python-cryptography
        python-dbus
        python-decorator
        python-distlib
        python-docutils
        python-dulwich
        python-executing
        python-fastjsonschema
        python-filelock
        python-findpython
        python-gobject
        python-html5lib
        python-idna
        python-imagesize
        python-installer
        python-ipython-pygments-lexers
        python-jaraco.classes
        python-jaraco.collections
        python-jaraco.context
        python-jaraco.functools
        python-jaraco.text
        python-jedi
        python-jeepney
        python-jinja
        python-jsonschema
        python-jsonschema-specifications
        python-keyring
        python-lark-parser
        python-linux-procfs
        python-lockfile
        python-lxml
        python-markupsafe
        python-matplotlib-inline
        python-more-itertools
        python-msgpack
        python-packaging
        python-parso
        python-pbs-installer
        python-pexpect
        python-pkginfo
        python-platformdirs
        python-poetry
        python-poetry-core
        python-poetry-plugin-export
        python-prompt_toolkit
        python-psutil
        python-ptyprocess
        python-pure-eval
        python-pycparser
        python-pygments
        python-pyproject-hooks
        python-pyte
        python-pytz
        python-pyudev
        python-pywal
        python-pyxdg
        python-rapidfuzz
        python-referencing
        python-requests
        python-requests-toolbelt
        python-roman-numerals-py
        python-rpds-py
        python-secretstorage
        python-setuptools
        python-shellingham
        python-six
        python-snowballstemmer
        python-sphinx
        python-sphinx-alabaster-theme
        python-sphinxcontrib-applehelp
        python-sphinxcontrib-devhelp
        python-sphinxcontrib-htmlhelp
        python-sphinxcontrib-jsmath
        python-sphinxcontrib-qthelp
        python-sphinxcontrib-serializinghtml
        python-stack-data
        python-tomlkit
        python-tqdm
        python-traitlets
        python-trove-classifiers
        python-typing_extensions
        python-urllib3
        python-virtualenv
        python-wcwidth
        python-webencodings
        python-wheel
        qca-qt6
        qqwing
        qrencode
        qt5-base
        qt5-declarative
        qt5-graphicaleffects
        qt5-quickcontrols2
        qt5-svg
        qt5-translations
        qt5-wayland
        qt5-x11extras
        qt5ct
        qt6-5compat
        qt6-base
        qt6-declarative
        qt6-multimedia
        qt6-multimedia-ffmpeg
        qt6-shadertools
        qt6-speech
        qt6-svg
        qt6-translations
        qt6-wayland
        qt6ct
        qemu-guest-agent
        raptor
        rav1e
        re2
        readline
        refind
        reflector
        retro-gtk
        ripgrep
        ripgrep-all
        rofi-wayland
        rp-pppoe
        rpcbind
        rsync
        rtkit
        rtmpdump
        rubberband
        rutabaga-ffi
        rxvt-unicode-terminfo
        sbc
        scdoc
        screen
        sdbus-cpp
        sddm
        sdl2-compat
        sdl2_image
        sdl3
        sdparm
        seabios
        seatd
        sed
        semver
        sequoia-sq
        serd
        sg3_utils
        shaderc
        shadow
        shared-mime-info
        simdjson
        slang
        sleuthkit
        slurp
        smartmontools
        smbclient
        snappy
        sndio
        sof-firmware
        solid
        sonnet
        sord
        sound-theme-freedesktop
        soundtouch
        spandsp
        spdlog
        speex
        speexdsp
        spice
        spice-gtk
        spice-protocol
        spirv-tools
        sqlite
        squashfs-tools
        sratom
        srt
        startup-notification
        strace
        sudo
        suitesparse
        supermin
        svt-av1
        svt-hevc
        swappy
        swaync
        swtmp
        syndication
        syntax-highlighting
        sysfsutils
        syslinux
        systemd-resolvconf
        taglib
        talloc
        tar
        tdb
        tcpdump
        telepathy-glib
        telepathy-idle
        telepathy-logger
        telepathy-mission-control
        template-glib
        terminus-font
        testdisk
        tevent
        texinfo
        thefuck
        thin-provisioning-tools
        thunar
        thunar-archive-plugin
        thunar-volman
        tinysparql
        tmux
        tomlplusplus
        totem-pl-parser
        tpm2-tools
        tpm2-tss
        tree-sitter
        tree-sitter-c
        tree-sitter-lua
        tree-sitter-markdown
        tree-sitter-query
        tree-sitter-vim
        tree-sitter-vimdoc
        tslib
        ttf-cascadia-code
        ttf-font-awesome
        ttf-jetbrains-mono-nerd
        ttf-liberation
        ttf-meslo-nerd
        ttf-nerd-fonts-symbols
        ttf-nerd-fonts-symbols-common
        tumbler
        tuned
        twolame
        tzdata
        uchardet
        udisks2
        udftools
        unibilium
        unzip
        upower
        usb_modeswitch
        usbredir
        usbmuxd
        usbutils
        util-linux
        util-linux-libs
        v4l-utils
        vala
        vapoursynth
        vde2
        vid.stab
        vim
        vim-runtime
        virglrenderer
        vmaf
        volume_key
        vpnc
        vte-common
        vte3
        vte4
        vulkan-icd-loader
        wavpack
        waybar
        wayland
        wayland-protocols
        webkit2gtk-4.1
        webkitgtk-6.0
        webp-pixbuf-loader
        webrtc-audio-processing-1
        wget
        which
        wildmidi
        wireless-regdb
        wireless_tools
        wireplumber
        wl-clipboard
        woff2
        wolfssl
        wpa_supplicant
        wvdial
        x264
        x265
        xcb-imdkit
        xcb-proto
        xcb-util
        xcb-util-cursor
        xcb-util-errors
        xcb-util-image
        xcb-util-keysyms
        xcb-util-renderutil
        xcb-util-wm
        xcur2png
        xdg-dbus-proxy
        xdg-desktop-portal
        xdg-desktop-portal-gtk
        xdg-desktop-portal-hyprland
        xdg-utils
        xf86-input-libinput
        xfconf
        xfsprogs
        xkeyboard-config
        xorg-fonts-encodings
        xorgproto
        xvidcore
        xxhash
        xz
        yara
        yazi
        yelp
        yelp-xsl
        yyjson
        zbar
        zeromq
        zimg
        zip
        zix
        zlib
        zlib-ng
        zoxide
        zram-generator
        zsh
        zstd
        zvbi
        zxing-cpp
xf86-input-libinput
xfconf
xfsprogs
xkeyboard-config
xorg-fonts-encodings
xorg-server
xorg-server-common
xorg-setxkbmap
xorg-xauth
xorg-xinit
xorg-xkbcomp
xorg-xmodmap
xorg-xprop
xorg-xrandr
xorg-xrdb
xorg-xset
xorgproto
xvidcore
xxhash
xz
yara
python
python-aiofiles
python-argcomplete
python-asttokens
python-atspi
python-attrs
python-autocommand
python-babel
python-build
python-cachecontrol
python-cachy
python-cairo
python-cffi
python-charset-normalizer
python-cleo
python-colorama
python-configobj
python-crashtest
python-cryptography
python-dbus
python-decorator
python-distlib
python-docutils
python-dulwich
python-executing
python-fastjsonschema
python-filelock
python-findpython
python-gobject
python-html5lib
python-idna
python-imagesize
python-installer
python-ipython-pygments-lexers
python-jaraco.classes
python-jaraco.collections
python-jaraco.context
python-jaraco.functools
python-jaraco.text
python-jedi
python-jeepney
python-jinja
python-jsonschema
python-jsonschema-specifications
python-keyring
python-lark-parser
python-linux-procfs
python-lockfile
python-lxml
python-markupsafe
python-matplotlib-inline
python-more-itertools
python-msgpack
python-packaging
python-parso
python-pbs-installer
python-pexpect
python-pkginfo
python-platformdirs
python-poetry
python-poetry-core
python-poetry-plugin-export
python-prompt_toolkit
python-psutil
python-ptyprocess
python-pure-eval
python-pycparser
python-pygments
python-pyproject-hooks
python-pyte
python-pytz
python-pyudev
python-pywal
python-pyxdg
python-rapidfuzz
python-referencing
python-requests
python-requests-toolbelt
python-roman-numerals-py
python-rpds-py
python-secretstorage
python-setuptools
python-shellingham
python-six
python-snowballstemmer
python-sphinx
python-sphinx-alabaster-theme
python-sphinxcontrib-applehelp
python-sphinxcontrib-devhelp
python-sphinxcontrib-htmlhelp
python-sphinxcontrib-jsmath
python-sphinxcontrib-qthelp
python-sphinxcontrib-serializinghtml
python-stack-data
python-tomlkit
python-tqdm
python-traitlets
python-trove-classifiers
python-typing_extensions
python-urllib3
python-virtualenv
python-wcwidth
python-webencodings
python-wheel
qca-qt6
qqwing
qrencode
qt5-base
qt5-declarative
qt5-graphicaleffects
qt5-quickcontrols2
qt5-svg
qt5-translations
qt5-x11extras
qt5ct
qt6-5compat
qt6-base
qt6-declarative
qt6-multimedia
qt6-multimedia-ffmpeg
qt6-shadertools
qt6-speech
qt6-svg
qt6-translations
qt6ct
raptor
rav1e
re2
readline
retro-gtk
ripgrep
ripgrep-all
rpcbind
rsync
rtkit
rtmpdump
rubberband
rutabaga-ffi
sbc
scdoc
sdbus-cpp
sddm
sdl2-compat
sdl2_image
sdl3
seabios
seatd
sed
semver
serd
shaderc
shadow
shared-mime-info
simdjson
slang
sleuthkit
smartmontools
smbclient
snappy
sndio
solid
sonnet
sord
sound-theme-freedesktop
soundtouch
spandsp
spdlog
speex
speexdsp
spice
spice-gtk
spice-protocol
spirv-tools
sqlite
squashfs-tools
sratom
srt
startup-notification
strace
sudo
suitesparse
supermin
svt-av1
svt-hevc
swappy
licenses
lilv
linux
linux-api-headers
linux-firmware
linux-firmware-whence
linux-headers
llhttp
llvm-libs
lm_sensors
lmdb
localsearch
lrzip
lsof
lsscsi
lua
lua51-lpeg
luajit
lv2
lvm2
lxappearance
lz4
lzo
lzop
m4
make
md4c
mdadm
media-player-info
mesa
meson
minizip
mjpegtools
mkinitcpio
mkinitcpio-busybox
mobile-broadband-provider-info
mpdecimal
mpfr
mpg123
mpv
mpv-mpris
msgpack-c
mtdev
mtools
mujs
multipath-tools
nano
ncurses
ndctl
neon
neovim
netpbm
nettle
network-manager-applet
networkmanager
nftables
nilfs-utils
ninja
nm-connection-editor
node-gyp
nodejs
nodejs-nopt
noto-fonts
noto-fonts-emoji
npm
npth
nspr
nss
ntfs-3g
numactl
nwg-look
ocl-icd
oniguruma
openal
opencore-amr
openexr
openh264
openjpeg2
openssh
openssl
opus
orc
os-prober
osinfo-db
ostree
p11-kit
pacman
pacman-contrib
pacman-mirrorlist
pahole
pam
pambase
pamixer
pango
pangomm
pangomm-2.48
parallel
parted
patch
pavucontrol
pciutils
pcre
pcre2
pcsclite
perf
perl
perl-error
perl-libintl-perl
perl-mailtools
perl-timedate
phodav
phonon-qt6
pinentry
pipewire
pipewire-alsa
pipewire-audio
pipewire-jack
pipewire-pulse
pixman
pkgconf
plasma-activities
playerctl
polkit
polkit-kde-agent
polkit-qt6
poppler
poppler-data
poppler-glib
poppler-qt6
popt
portaudio
power-profiles-daemon
procps-ng
protobuf
psmisc
pugixml
groff
grub
gsettings-desktop-schemas
gsettings-system-schemas
gsfonts
gsm
gsound
gspell
gssdp
gst-plugin-pipewire
gst-plugins-bad
gst-plugins-bad-libs
gst-plugins-base
gst-plugins-base-libs
gst-plugins-good
gstreamer
gtest
gtk-doc
gtk-layer-shell
gtk-update-icon-cache
gtk-vnc
gtk2
gtk3
gtk4
gtkmm-4.0
gtkmm3
gtksourceview4
gtksourceview5
gts
guestfs-tools
guile
gum
gupnp
gupnp-av
gupnp-dlna
gupnp-igd
gzip
harfbuzz
harfbuzz-icu
hdparm
hicolor-icon-theme
hidapi
highway
hivex
htop
hwdata
hyphen
iana-etc
icu
ijs
imagemagick
imath
imlib2
iniparser
intel-ucode
iproute2
iptables
iputils
ipython
iso-codes
iwd
jansson
jasper
jbig2dec
jbigkit
jfsutils
jq
js128
json-c
json-glib
jsoncpp
jsonrpc-glib
karchive
kauth
kbd
kbookmarks
kcmutils
kcodecs
kcolorscheme
kcompletion
kconfig
kconfigwidgets
kcoreaddons
kcrash
kdbusaddons
kdnssd
kdsoap-qt6
kdsoap-ws-discovery-client
keyutils
kfilemetadata
kglobalaccel
kguiaddons
ki18n
kiconthemes
kidletime
kio
kio-extras
kirigami
kitemviews
kitty
kitty-shell-integration
kitty-terminfo
kjobwidgets
kmod
knewstuff
knotifications
kpackage
kparts
krb5
kservice
ktextwidgets
kuserfeedback
kvantum
kvantum-qt5
kwallet
kwidgetsaddons
kwindowsystem
kxmlgui
l-smash
lame
lapack
lcms2
ldb
leancrypto
lensfun
less
capstone
cava
cdparanoia
cdrtools
chromaprint
chromium
cifs-utils
clang
cliphist
clutter
clutter-gst
clutter-gtk
cmark
cogl
compiler-rt
composefs
convertlit
coreutils
cpio
cracklib
cryptsetup
ctags
curl
dav1d
db5.3
dbus
dbus-broker
dbus-broker-units
dbus-glib
dbus-units
dconf
debootstrap
default-cursors
desktop-file-utils
device-mapper
dhcpcd
dialog
diffutils
distro-info
distro-info-data
dkms
dleyna
dnsmasq
docbook-xml
docbook-xsl
dosfstools
double-conversion
dtc
duktape
e2fsprogs
ebook-tools
editorconfig-core-c
edk2-aarch64
edk2-arm
edk2-ovmf
efibootmgr
efivar
egl-gbm
egl-x11
eglexternalplatform
elfutils
ell
enchant
erofs-utils
ethtool
evolution-data-server
exempi
exfatprogs
exiv2
exo
expat
eza
f2fs-tools
faac
faad2
fakeroot
fastfetch
ffmpeg
ffmpegthumbnailer
ffnvcodec-headers
fftw
figlet
file
filesystem
findutils
flac
flatpak
flex
fluidsynth
fmt
folks
fontconfig
freeglut
freetype2
frei0r-plugins
fribidi
fuse-common
fuse2
fuse3
fzf
gawk
gc
gcc
gcc-libs
gcr
gcr-4
gd
gdbm
gdk-pixbuf2
gegl
geocode-glib-2
geocode-glib-common
gettext
gfxstream
ghostscript
giflib
git
gjs
glib-networking
glib2
glib2-docs
glibc
glibmm
glibmm-2.68
glm
glslang
glu
glusterfs
gmime3
gmp
gnu-free-fonts
gnulib-l10n
gnupg
gnutls
go
gobject-introspection-runtime
gom
gperftools
gpgme
gpgmepp
gpm
gptfdisk
granite
graphene
graphite
graphviz
grep
grilo
aalib
abseil-cpp
acl
adwaita-cursors
adwaita-fonts
adwaita-icon-theme
adwaita-icon-theme-legacy
alsa-card-profiles
alsa-lib
alsa-topology-conf
alsa-ucm-conf
aom
appstream
aquamarine
arch-install-scripts
archiso
archlinux-keyring
at-spi2-core
atkmm
attica
attr
audit
augeas
autoconf
autoconf-archive
automake
avahi
babl
baloo
baloo-widgets
base
base-devel
bash
bat
binutils
bison
blas
bluez-libs
breeze-icons
brltty
brotli
btop
btrfs-progs
bubblewrap
bzip2
    )
    
    info "Installing ${#wavesos_packages[@]} WavesOS packages..."
    
    for i in "${!wavesos_packages[@]}"; do
        local current=$((i + 1))
        show_progress "$current" "${#wavesos_packages[@]}" "Installing ${wavesos_packages[$i]}..."
        
        if ! pacstrap /mnt "${wavesos_packages[$i]}" 2>/dev/null; then
            warning "Failed to install ${wavesos_packages[$i]}, continuing..."
        fi
    done
    
    success "WavesOS comprehensive packages installation completed"
}

# AUR packages function  
install_aur_packages() {
    section_header "System • AUR Packages"
    log "Installing AUR packages using yay..."
    
    local aur_packages=(
        pyprland
        grimblast-git
        yay
        wvkbd
        zen-browser-bin
        kando-bin
        kora-icon-theme
        sweet-cursors-hyprcursor-git
        aura
    )
    
    info "Installing ${#aur_packages[@]} AUR packages..."
    
    for i in "${!aur_packages[@]}"; do
        local current=$((i + 1))
        show_progress "$current" "${#aur_packages[@]}" "Installing ${aur_packages[$i]}..."
        
        if ! arch-chroot /mnt su - "$USERNAME" -c "yay -S --noconfirm ${aur_packages[$i]}" 2>/dev/null; then
            warning "Failed to install ${aur_packages[$i]}, continuing..."
        fi
    done
    
    success "AUR packages installation completed"
}

# Hyprland-specific packages
install_hyprland_packages() {
    section_header "Desktop • Hyprland Environment"
    log "Installing Hyprland desktop environment..."
    
    local hyprland_packages=(
       hyprcursor
hyprgraphics
hypridle
hyprland
hyprland-qt-support
hyprland-qtutils
hyprlang
hyprlock
hyprpolkitagent
hyprsunset
hyprutils
hyprwayland-scanner
xdg-desktop-portal-hyprland
waybar
wayland
wayland-protocols
wl-clipboard
rofi-wayland
swaync
swappy
slurp
grim
    )
    
    info "Installing ${#hyprland_packages[@]} Hyprland packages..."
    
    for i in "${!hyprland_packages[@]}"; do
        local current=$((i + 1))
        show_progress "$current" "${#hyprland_packages[@]}" "Installing ${hyprland_packages[$i]}..."
        
        if ! pacstrap /mnt "${hyprland_packages[$i]}" 2>/dev/null; then
            warning "Failed to install ${hyprland_packages[$i]}, continuing..."
        fi
    done
    
    success "Hyprland desktop environment installation completed"
}

# GNOME-specific packages
install_gnome_packages() {
    section_header "Desktop • GNOME Environment"
    log "Installing GNOME desktop environment..."
    
    local gnome_packages=(
   gnome
gnome-extra
gsettings-desktop-schemas
gsettings-system-schemas
adwaita-cursors
adwaita-fonts
adwaita-icon-theme
adwaita-icon-theme-legacy
at-spi2-core
glib2
glib2-docs
glib-networking
glibmm
glibmm-2.68
gvfs
gvfs-mtp
dconf
gtk2
gtk3
gtk4
gtk-doc
gtk-layer-shell
gtk-update-icon-cache
gtk-vnc
gtkmm-4.0
gtkmm3
gtksourceview4
gtksourceview5
evolution-data-server
folks
gom
geocode-glib-2
geocode-glib-common
grilo
polkit-gnome
    )
    
    info "Installing ${#gnome_packages[@]} GNOME packages..."
    
    for i in "${!gnome_packages[@]}"; do
        local current=$((i + 1))
        show_progress "$current" "${#gnome_packages[@]}" "Installing ${gnome_packages[$i]}..."
        
        if ! pacstrap /mnt "${gnome_packages[$i]}" 2>/dev/null; then
            warning "Failed to install ${gnome_packages[$i]}, continuing..."
        fi
    done
    
    success "GNOME desktop environment installation completed"
}

# Main desktop environment installation function
install_desktop_environment() {
    # Install specific packages based on selection
    case "$SELECTED_DE" in
        "hyprland")
            install_hyprland_packages
            ;;
        "gnome")
            install_gnome_packages
            ;;
        "both")
            install_hyprland_packages
            install_gnome_packages
            ;;
        *)
            error "Invalid desktop environment selection: $SELECTED_DE"
            ;;
    esac
}

# Legacy function - now replaced by install_comprehensive_packages
# Keeping for reference but should not be called
_legacy_install_custom_packages() {
    section_header "System • Legacy Custom Packages (DEPRECATED)"
    log "This function has been merged into install_comprehensive_packages..."
    
    local deprecated_packages=(
        # This massive list has been moved to install_comprehensive_packages
        # Original list had 900+ packages - truncated for space
        # Use install_comprehensive_packages instead
    )
    
    warning "This function is deprecated. Use install_comprehensive_packages instead."
    success "Legacy function call completed - no packages installed"
}
